name: Build
on:
  push:
    branches: [master, branch-*, dogfood-*]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Build and Test
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.11.2

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            development/artifactory/token/${{ github.repository_owner }}-${{ github.event.repository.name }}-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;

      - name: Configure npm registry
        run: |
          npm config set //repox.jfrog.io/artifactory/api/npm/:_authToken=${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
          npm config set registry https://repox.jfrog.io/artifactory/api/npm/npm/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npx knip
          (cd build && npm pack)
        env:
          VERSION: SNAPSHOT

      - name: Test
        run: npm test

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-artifacts
          path: |
            build/
            coverage/
            node_modules/
            test-report.xml
          if-no-files-found: error

  qa-linux:
    name: QA Linux
    needs: build
    runs-on: github-ubuntu-latest-s
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
    steps: &qa-steps
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.11.2
          mise_toml: |
            [tools]
            java = "21.0"

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: build-artifacts
          path: .

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            development/artifactory/token/${{ github.repository_owner }}-${{ github.event.repository.name }}-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;

      - name: Configure npm registry
        run: |
          npm config set //repox.jfrog.io/artifactory/api/npm/:_authToken=${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
          npm config set registry https://repox.jfrog.io/artifactory/api/npm/npm/

      - name: Run integration tests
        env:
          ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
        run: npm run test-integration
        shell: bash

  qa-windows:
    name: QA Windows
    needs: build
    runs-on: windows-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
    steps: *qa-steps

  analyze:
    name: Analyze in SonarCloud
    needs: build
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.11.2

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: build-artifacts
          path: .

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            development/kv/data/sonarcloud token | SONAR_TOKEN;

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: node ./ci-analysis.js
