name: Build
on:
  push:
    branches: [master, branch-*, dogfood-*]
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Build and Test
    runs-on: github-ubuntu-latest-s
    outputs:
      build-number: ${{ steps.build.outputs.build-number }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12

      - uses: SonarSource/ci-github-actions/build-npm@v1
        id: build
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          sonar-platform: 'none'

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-artifacts
          path: |
            build/
            coverage/
          if-no-files-found: error

  qa-linux:
    name: QA Linux
    needs: build
    runs-on: github-ubuntu-latest-s
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: build-artifacts
          path: .

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            development/artifactory/token/${{ github.repository }}-qa-deployer access_token | ARTIFACTORY_DEPLOY_ACCESS_TOKEN;

      - name: Setup integration test
        run: |
          (cd build && npm pack)
          cp build/sonar-scan-SNAPSHOT.tgz test/integration
          (cd test/integration && npm install --no-save sonar-scan-SNAPSHOT.tgz)
          (cd tools/orchestrator && npm run build)

      - name: Run integration tests
        env:
          ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_DEPLOY_ACCESS_TOKEN }}
        run: npm run test-integration

  qa-windows:
    name: QA Windows
    needs: build
    runs-on: windows-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: build-artifacts
          path: .

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            development/artifactory/token/${{ github.repository }}-qa-deployer access_token | ARTIFACTORY_DEPLOY_ACCESS_TOKEN;

      - name: Setup integration test
        run: |
          cd build && npm pack
          copy build/sonar-scan-SNAPSHOT.tgz test/integration
          cd test/integration && npm install --no-save sonar-scan-SNAPSHOT.tgz
          cd tools/orchestrator && npm run build
        shell: cmd

      - name: Run integration tests
        env:
          ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_DEPLOY_ACCESS_TOKEN }}
        run: npm run test-integration

  knip:
    name: Knip
    needs: build
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12

      - name: Install dependencies and run knip
        run: |
          npm install --no-package-lock
          npm run build
          npx knip

  analyze:
    name: Analyze in ${{ matrix.platform_name }}
    needs: build
    runs-on: github-ubuntu-latest-s
    if: matrix.is_shadow == false || github.event_name == 'schedule'
    strategy:
      matrix:
        include:
          - platform_name: SonarCloud
            vault_path: development/kv/data/sonarcloud
            host_url: https://sonarcloud.io
            is_shadow: false
          - platform_name: SQ NEXT
            vault_path: development/kv/data/next
            host_url: https://next.sonarqube.com/sonarqube
            is_shadow: true
          - platform_name: SonarQube.us
            vault_path: development/kv/data/sonarqube-us
            host_url: https://sonarqube.us
            is_shadow: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: build-artifacts
          path: .

      - uses: SonarSource/vault-action-wrapper@v3
        id: secrets
        with:
          secrets: |
            ${{ matrix.vault_path }} token | SONAR_TOKEN;

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ matrix.host_url }}
        run: node ./scripts/ci-analysis.js

  iris:
    name: IRIS
    needs: analyze
    runs-on: github-ubuntu-latest-s
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: SonarSource_sonar-scanner-npm
          primary_platform: SQC-EU
          shadow1_project_key: SonarSource_sonar-scanner-npm
          shadow1_platform: Next
          shadow2_project_key: SonarSource_sonar-scanner-npm
          shadow2_platform: SQC-US
